<script lang="ts">
	import { adminApi } from '$api/admin';
	import { errorMessage } from '$api/errors';
	import { toast } from '$stores/toast.svelte';
	import { i18n, intlLocale } from '$lib/i18n';
	import type { Capability, CapabilityCatalogueEntry, UserCapability } from '$lib/types';
	import Button from '$components/ui/Button.svelte';
	import Input from '$components/ui/Input.svelte';
	import Modal from '$components/ui/Modal.svelte';
	import Select from '$components/ui/Select.svelte';
	import CapabilityBadge from '$components/ui/CapabilityBadge.svelte';
	import ConfirmDangerousDialog from '$components/ui/ConfirmDangerousDialog.svelte';
	import Skeleton from '$components/ui/Skeleton.svelte';
	import { ShieldPlus, X, Info } from '@lucide/svelte';

	interface Props {
		userId: string;
	}

	let { userId }: Props = $props();

	// The grantable set comes from `GET /admin/capabilities` and is not
	// enumerated here. It used to be, anchored to a CHECK constraint that
	// migration 0404 had already replaced with a table — and the copy was
	// wrong: `mission_arbiter`, `security_triager` and `domain_curator:design`
	// were missing, so three shipped screens could be reached by nobody but a
	// global admin. Part of the catalogue is generated by a trigger on
	// `orientations`, so no copy of it can stay right on its own (SKI-351).
	let catalogue = $state<CapabilityCatalogueEntry[]>([]);
	let catalogueFailed = $state(false);

	/** Translate, or fall back to what was passed.
	 *
	 *  `i18n.t` echoes the key when nothing matches. The catalogue can name a
	 *  capability no locale pass has seen yet, and a raw slug is a far better
	 *  label for it than `admin.capabilities.names.foo`. */
	function tr(key: string, fallback: string): string {
		const out = i18n.t(key);
		return out === key ? fallback : out;
	}

	/** Label for the grant dropdown. Scoped capabilities render as
	 *  "<family> — <scope>" with the scope verbatim: it is the same slug that
	 *  sits on `orientations.reviewer_group`, and translating it would
	 *  decouple the label from the value being granted. */
	function capabilityLabel(c: Capability): string {
		const colon = c.indexOf(':');
		if (colon === -1) return tr(`admin.capabilities.names.${c}`, c);
		const family = c.slice(0, colon);
		const scope = c.slice(colon + 1);
		return `${tr(`admin.capabilities.families.${family}`, family)} — ${scope}`;
	}

	/** What granting it actually does.
	 *
	 *  A local translation when there is one, the catalogue's own sentence
	 *  otherwise. The served descriptions are French only, so preferring the
	 *  locale file keeps the known set translated — and falling through to
	 *  the server keeps the generated rows described at all, which matters
	 *  more than keeping them in the reader's language. */
	function capabilityDescription(entry: CapabilityCatalogueEntry): string {
		const local = entry.scope
			? i18n.t(`admin.capabilities.familyDescriptions.${entry.family}`, { scope: entry.scope })
			: i18n.t(`admin.capabilities.descriptions.${entry.capability}`);
		return local.startsWith('admin.capabilities.') ? entry.description : local;
	}

	let active = $state<UserCapability[]>([]);
	let loading = $state(true);

	let showGrant = $state(false);
	let granting = $state(false);
	let grantCapability = $state<Capability | ''>('');
	let grantReason = $state('');
	let grantExpiresAt = $state('');
	let grantTouched = $state(false);

	let revokeTarget = $state<Capability | null>(null);
	let revoking = $state(false);

	const activeSet = $derived(new Set(active.map((c) => c.capability)));

	// Served ordered by family then scope, so the reviewer families of one
	// domain arrive together. That is the order somebody reads a list of
	// forty in, so it is kept rather than re-sorted alphabetically here.
	const grantOptions = $derived(
		catalogue.map((e) => ({
			value: e.capability,
			label: capabilityLabel(e.capability),
			disabled: activeSet.has(e.capability)
		}))
	);

	const selectedEntry = $derived(
		grantCapability === '' ? null : (catalogue.find((e) => e.capability === grantCapability) ?? null)
	);

	const grantReasonError = $derived.by(() => {
		if (!grantTouched) return null;
		const trimmed = grantReason.trim();
		if (trimmed.length === 0) return i18n.t('admin.confirmDialog.reasonRequired');
		if (trimmed.length < 8)
			return i18n.t('admin.confirmDialog.reasonTooShort', { n: 8 });
		return null;
	});

	const canSubmitGrant = $derived(
		!granting && grantCapability !== '' && grantReasonError === null && grantReason.trim().length >= 8
	);

	$effect(() => {
		void load();
		void loadCatalogue();
	});

	async function load() {
		loading = true;
		try {
			const res = await adminApi.listUserCapabilities(userId);
			active = res.data.capabilities;
		} catch (e) {
			toast.error(errorMessage(e));
		} finally {
			loading = false;
		}
	}

	/** The grantable set, loaded beside the user's own list.
	 *
	 *  A failure here disables granting instead of opening an empty dropdown.
	 *  A picker with nothing in it reads as "this user can hold nothing",
	 *  which is a different statement and a false one — and it is the kind of
	 *  false statement an operator acts on. */
	async function loadCatalogue() {
		try {
			const res = await adminApi.capabilityCatalogue();
			catalogue = res.data;
			catalogueFailed = false;
		} catch {
			catalogue = [];
			catalogueFailed = true;
		}
	}

	function openGrant() {
		grantCapability = '';
		grantReason = '';
		grantExpiresAt = '';
		grantTouched = false;
		showGrant = true;
	}

	async function submitGrant() {
		grantTouched = true;
		if (!canSubmitGrant || grantCapability === '') return;
		granting = true;
		try {
			await adminApi.grantCapability(userId, {
				capability: grantCapability,
				granted_reason: grantReason.trim(),
				expires_at: grantExpiresAt ? new Date(grantExpiresAt).toISOString() : undefined
			});
			toast.success(i18n.t('admin.capabilities.grantSuccess'));
			showGrant = false;
			await load();
		} catch (e) {
			toast.error(errorMessage(e));
		} finally {
			granting = false;
		}
	}

	function requestRevoke(cap: Capability) {
		revokeTarget = cap;
	}

	/** What revoking this one will actually do.
	 *
	 *  For an engine-managed capability the honest answer is "not much": the
	 *  next recompute grants it again. Saying so in the dialog is the whole
	 *  value of the flag — somebody who does not know spends an afternoon
	 *  wondering why the revoke did not take. */
	function revokeDialogDescription(cap: Capability): string {
		const base = i18n.t('admin.capabilities.revokeDialogDescription');
		const entry = catalogue.find((e) => e.capability === cap);
		return entry?.engine_managed
			? `${base} ${i18n.t('admin.capabilities.revokeEngineManagedWarning')}`
			: base;
	}

	async function confirmRevoke() {
		if (!revokeTarget || revoking) return;
		revoking = true;
		const cap = revokeTarget;
		try {
			await adminApi.revokeCapability(userId, cap);
			toast.success(i18n.t('admin.capabilities.revokeSuccess'));
			revokeTarget = null;
			await load();
		} catch (e) {
			toast.error(errorMessage(e));
		} finally {
			revoking = false;
		}
	}

	function fmtExpires(iso: string | null): string | null {
		if (!iso) return null;
		try {
			return new Date(iso).toLocaleDateString(intlLocale(), {
				day: '2-digit',
				month: 'short',
				year: 'numeric'
			});
		} catch {
			return iso;
		}
	}
</script>

<section class="mb-6 rounded-2xl border border-border bg-surface-elevated p-5">
	<div class="mb-3 flex items-center justify-between gap-3">
		<div class="flex items-center gap-2">
			<ShieldPlus size={16} strokeWidth={2} class="text-primary" />
			<h2 class="text-sm font-semibold uppercase tracking-wider text-text-muted">
				{i18n.t('admin.capabilities.sectionTitle')}
			</h2>
		</div>
		<Button variant="primary" size="sm" onclick={openGrant} disabled={loading || catalogueFailed}>
			<ShieldPlus size={14} strokeWidth={2} />
			{i18n.t('admin.capabilities.grantBtn')}
		</Button>
	</div>

	<p class="mb-4 text-xs text-text-muted">{i18n.t('admin.capabilities.sectionHint')}</p>

	{#if catalogueFailed}
		<p class="mb-4 rounded-xl border border-warning/40 bg-warning/10 px-3 py-2 text-xs text-warning">
			{i18n.t('admin.capabilities.catalogueUnavailable')}
		</p>
	{/if}

	{#if loading}
		<div class="flex flex-col gap-2">
			<Skeleton class="h-10 w-full" rounded="xl" />
			<Skeleton class="h-10 w-full" rounded="xl" />
		</div>
	{:else if active.length === 0}
		<p class="rounded-xl border border-border bg-surface-overlay px-4 py-6 text-center text-sm text-text-muted">
			{i18n.t('admin.capabilities.empty')}
		</p>
	{:else}
		<ul class="flex flex-col gap-2">
			{#each active as cap (cap.capability)}
				<li class="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border bg-surface-overlay px-3 py-2">
					<div class="flex min-w-0 flex-1 flex-wrap items-center gap-2">
						<CapabilityBadge capability={cap.capability} size="md" />
						{#if cap.expires_at}
							<span class="text-xs text-warning">
								{i18n.t('admin.capabilities.expiresAtLabel')} : {fmtExpires(cap.expires_at)}
							</span>
						{/if}
						{#if cap.granted_reason && cap.granted_reason !== 'unspecified'}
							<span class="min-w-0 text-xs text-text-muted truncate">
								{i18n.t('admin.capabilities.grantedByLabel')} {cap.granted_reason}
							</span>
						{/if}
					</div>
					<Button variant="ghost" size="sm" onclick={() => requestRevoke(cap.capability)}>
						<X size={14} strokeWidth={2} />
						{i18n.t('admin.capabilities.revokeBtn')}
					</Button>
				</li>
			{/each}
		</ul>
	{/if}

	<p class="mt-3 flex items-start gap-2 text-xs text-text-muted">
		<Info size={12} strokeWidth={2} class="mt-0.5 shrink-0" />
		<span>{i18n.t('admin.capabilities.historyDeferred')}</span>
	</p>
</section>

<Modal
	open={showGrant}
	title={i18n.t('admin.capabilities.grantDialogTitle')}
	onclose={() => (showGrant = false)}
	size="md"
>
	<div class="flex flex-col gap-4">
		<div class="flex flex-col gap-1.5">
			<label for="cap-select" class="text-sm font-medium text-text-primary">
				{i18n.t('admin.capabilities.grantCapabilityLabel')}
			</label>
			<Select
				items={grantOptions}
				bind:value={grantCapability}
				placeholder={i18n.t('admin.capabilities.grantCapabilityLabel')}
				shape="rounded"
				searchable
			/>
			{#if selectedEntry}
				<p class="text-xs text-text-muted">
					{capabilityDescription(selectedEntry)}
				</p>
				<div class="flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-text-muted">
					<span>
						{i18n.t('admin.capabilities.heldByLabel', { n: selectedEntry.held_by })}
					</span>
					{#if selectedEntry.engine_managed}
						<!-- Grantable by hand, but the engine re-grants it on the next
						     recompute — so it is the revoke that will not stick, and
						     that is the half worth warning about. -->
						<span class="text-warning">{i18n.t('admin.capabilities.engineManagedNote')}</span>
					{/if}
					{#if selectedEntry.is_derived}
						<span>{i18n.t('admin.capabilities.derivedNote')}</span>
					{/if}
				</div>
			{/if}
		</div>

		<Input
			label={i18n.t('admin.capabilities.grantReasonLabel')}
			placeholder={i18n.t('admin.capabilities.grantReasonPlaceholder')}
			hint={i18n.t('admin.capabilities.grantReasonHint')}
			bind:value={grantReason}
			oninput={() => (grantTouched = true)}
			error={grantReasonError ?? undefined}
			data-testid="grant-cap-reason"
		/>

		<div class="flex flex-col gap-1.5">
			<label for="cap-expires" class="text-sm font-medium text-text-primary">
				{i18n.t('admin.capabilities.grantExpiresLabel')}
			</label>
			<input
				id="cap-expires"
				type="datetime-local"
				bind:value={grantExpiresAt}
				class="h-11 w-full rounded-xl border border-border bg-surface-elevated px-4 text-sm text-text-primary transition-colors focus:border-primary focus:ring-1 focus:ring-primary"
			/>
			<p class="text-xs text-text-muted">{i18n.t('admin.capabilities.grantExpiresHint')}</p>
		</div>
	</div>

	{#snippet actions()}
		<Button variant="secondary" size="sm" onclick={() => (showGrant = false)} disabled={granting}>
			{i18n.t('admin.common.cancel')}
		</Button>
		<Button
			variant="primary"
			size="sm"
			onclick={submitGrant}
			disabled={!canSubmitGrant}
			loading={granting}
			data-testid="grant-cap-submit"
		>
			{i18n.t('admin.capabilities.grantSubmitBtn')}
		</Button>
	{/snippet}
</Modal>

<ConfirmDangerousDialog
	open={revokeTarget !== null}
	title={i18n.t('admin.capabilities.revokeDialogTitle')}
	description={revokeTarget
		? capabilityLabel(revokeTarget) + ' — ' + revokeDialogDescription(revokeTarget)
		: ''}
	actionLabel={i18n.t('admin.capabilities.revokeBtn')}
	requireReason={false}
	loading={revoking}
	onconfirm={() => confirmRevoke()}
	onclose={() => (revokeTarget = null)}
/>
